import { collection, getDocs, getFirestore } from "firebase/firestore";
import { db } from "@/firebase/firebase.config";

import { useEffect, useState } from "react";

import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

import Wimmy from '../public/Wimmy Front.svg'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import PlayerCard from '@/components/PlayerCard'
import UserLogin from "@/firebase/UserLogin";

export default function Home() {
  const [users, setUsers] = useState([]);

  const getData = async () => {
    const querySnapshot = await getDocs(collection(db, "users"));
    const dbUsers = [];

    querySnapshot.forEach((doc) => {
      console.log(doc.id, " => ", doc.data());
      dbUsers.push({
        ...doc.data(),
        id: doc.id
      });
    });

    setUsers([
      ...dbUsers
    ]);
  }

  useEffect(() => {
    getData()
  }, [])

  const sortByPoints = (a, b) => {
    return b.wimPoints - a.wimPoints
  }

  return (
    <>
      <Head>
        <title>Brainwaves Leaderboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className={styles.main}>
        <NavBar />
        <Image src={Wimmy} height={300} width={300} />
        <div className={styles.text__container}>
          <h1 className={styles.title}>Brainwaves Progress Leaderboard</h1>
          <h3 className={styles.subtitle}>Check your progress rankings against other brainwaves users!</h3>
        </div>
        <UserLogin />
        <div className={styles.card__container}>
          {
            users.sort(sortByPoints).map((user, index) => {
              return (
                <PlayerCard
                  key={user.id}
                  color='#0C7BDC'
                  name={user.userName}
                  level={user.wimPoints}
                  progBG='#005AB5'
                  logicProg={user.logicProg}
                  patternProg={user.patternProg}
                  numberProg={user.numberProg}
                  rank={index + 1}
                />
              )
            })
          }
        </div>
        <Footer />
      </main>
    </>
  )
}
